### ISSUE TITLE
amplicon pre-preparation file generator notebook: generate warning if invalid characters found in sample_name

### ISSUE THREAD

**Issue by mmbryant23** [biocore/metagenomics_pooling_notebook#119]
Currently when a sample_name containing a character that is not acceptable in Qiita goes through the amplicon notebook, there is no warning produced and the user can go on to making a pre-preparation file that includes invalid characters. It would be beneficial to add a warning that does not allow the user to move forward unless all sample_name characters are confirmed valid.

For example, if someone names a BLANK sample BLANK.L'OREAL.2.4E, no warning or error will appear (but ' is not an acceptable character in a sample_name).

Thanks!

**Comment by mmbryant23** [comment]
Not sure if this counts as an invalid character, but it would also be beneficial if the notebook yields an error if there are spaces in the beginning or end of a sample_name (ie 'LAMI.RD317.D23.C1 ')

**Comment by charles-cowart** [comment]
> Not sure if this counts as an invalid character, but it would also be beneficial if the notebook yields an error if there are spaces in the beginning or end of a sample_name (ie 'LAMI.RD317.D23.C1 ')

@mmbryant23 would it be preferable to automatically remove any whitespaces at the beginning or ending of a sample-name? That might be more user-friendly.

**Comment by mmbryant23** [comment]
I think it would be great if it could be removed automatically but yield a
note saying something along the lines of “sample ‘x ‘ contained spaces
before or after the sample name. The space(s) was/were removed. OK to
proceed.”
Would that be possible? That way things are performed automatically,
increasing user friendliness, while also letting the user know the spaces
were there.
Let me know what you think, and thanks for working on this!

**Comment by charles-cowart** [comment]
Agreed! Adding now.

**Comment by charles-cowart** [comment]
Tentative solution found in https://github.com/biocore/metagenomics_pooling_notebook/pull/136.
