### ISSUE TITLE
metagenomics_pooling_notebook: Well_description in novaseq samplesheet should have the same format as well_description in the amplicon pre-preparation file

### ISSUE THREAD

**Issue by mmbryant23** [biocore/metagenomics_pooling_notebook#120]
Currently the Well_description column in a NovaSeq samplesheet contains only the sample name formatted in a Qiita-friendly manner. This is not useful and it would be beneficial if the format of the Well_description in the Novaseq samplesheet to contain the same information as the well_description in the amplicon pre-preparation file. I think this should affect both metagenomics pooling notebooks being used to generate sample sheets (metagenomics_pipeline_MiniPiconorm.ipynb and metagenomics_pipeline_iSeqnorm.ipynb)

Current amplicon pre-preparation file format: (project_name).(project_plate).(well_id)
Example: ABTX_11052_Plate_191.8.18.20.RK.ST.1315.A1

Current NovaSeq samplesheet format: (Sample_Name)
Proposed NovaSeq samplesheet format: (Sample_Plate).(Sample_Name).(Sample_Well)

Example:
**Current:**
<img width="930" alt="Screen Shot 2023-04-28 at 4 52 31 PM" src="https://user-images.githubusercontent.com/91337806/235252821-0c8a3499-cbeb-4eb5-a065-e0f03c031cbf.png">

**Proposed:**
<img width="1182" alt="Screen Shot 2023-04-28 at 4 53 43 PM" src="https://user-images.githubusercontent.com/91337806/235252833-f7849150-514a-427b-b5be-4c8dd3769632.png">

Additional information from Rodolfo regarding the code in the metagenomics pooling notebook:
<img width="1013" alt="Screen Shot 2023-04-28 at 4 07 24 PM" src="https://user-images.githubusercontent.com/91337806/235243723-d601b97c-9eb3-406b-bb30-2fd1e13a6c7b.png">

**Comment by charles-cowart** [comment]
Confirmed the code in amplicon_pre_prep_file_generator notebook uses the generate_qiita_prep_file() in metapool to generate well_descriptions of the form sample_plate' + 'sample_name' + 'well_id' columns.

**Comment by charles-cowart** [comment]
Addressed in https://github.com/biocore/metagenomics_pooling_notebook/pull/137
