### ISSUE TITLE
need well_id_96 information added to metagenomics samplesheets

### ISSUE THREAD

**Issue by mmbryant23** [biocore/metagenomics_pooling_notebook#122]
Currently well_id_96 information is not being exported into NovaSeq samplesheets and therefore not being carried over into the preparation file for the sequencing run. The steps to do this are as follows:
1) well_id_96 information column is inputed into the notebook via the 384-well compressed gDNA plate map (this is **complete**)
2) well_id_96 information column needs to be exported into the NovaSeq samplesheet information via the metagenomics pooling notebook (this is **needed**)
3) well_id_96 information column is carried over from the samplesheet into the preparation file generated by the SPP (i believe this has been completed for MiSeq amplicon pre-preparation files, but there may be additional changes needed for this to happen with NovaSeq samplesheets)

**Comment by mmbryant23** [comment]
After well_id_96 is successfully added, I believe we should changing the naming of "well_id" in the amplicon pre-preparation file to "well_id_384", and "Sample_Well" in the NovaSeq samplesheet to "well_id"384". This will specify in what plate the wells are being referred to, standardize naming format, and introduce consistency between amplicon and shotgun column names.

This change will likely affect the notebooks and likely SPP for amplicon and shotgun.

**Comment by charles-cowart** [comment]
> After well_id_96 is successfully added, I believe we should changing the naming of "well_id" in the amplicon pre-preparation file to "well_id_384", and "Sample_Well" in the NovaSeq samplesheet to "well_id"384". This will specify in what plate the wells are being referred to, standardize naming format, and introduce consistency between amplicon and shotgun column names.
> 
> This change will likely affect the notebooks and likely SPP for amplicon and shotgun.

Hi @mmbryant23! Just to clarify, both well_id and Sample_Well are going to be changed to well_id_384? Or does Sample_Well need to be changed into something else instead?

**Comment by mmbryant23** [comment]
Yes, both well_id (pre-preparation file for amplicon) and Sample Well
(samplesheet for metagenomics) are going to be changed to well_id_384.
This will introduce standardized naming between well_id formats (96 vs 384)
and harmonize the naming between amplicon + metaG/T.
Thanks for checking!

**Comment by mmbryant23** [comment]
Sure thing - I'm available at 11am if you want to chat - Can you please
send over the zoom link via email? Thanks!

**Comment by charles-cowart** [comment]
Addressed by https://github.com/biocore/metagenomics_pooling_notebook/pull/138
