### ISSUE TITLE
amplicon notebook: error should be raised when plate map and notebook project names do not match

### ISSUE THREAD

**Issue by mmbryant23** [biocore/metagenomics_pooling_notebook#125]
We would like the notebook to raise an error when the Project Name in the 384-well plate map does not match the Project_Name in the plate processing information in Step 2 of the notebook.

Currently if they are different, it appears like the notebook uses the Project Name in the 384-well plate map to generate the project_name field in the pre-preparation file (not the Project Name field in the notebook). If that project name is wrong, that incorrect information is carried through to the pre-preparation file output.

We’d like to instate a check to make sure that the Project Name(s) in the 384-well plate maps match the Project_Name(s) in the plate processing information input in step 2 of the notebook. This will ensure that both sources are consistent and the pre-preparation file project_name matches both sources.

**Comment by RodolfoSalido** [comment]
It is worth noting that we are hoping to move towards a notebook interface where plate_maps are imported directly into the notebook from the VisionMate output files, completely circumventing the Plate Compression spreadsheet, so discrepancies like this will be avoided in the near future. 

-Rodolfo
