### ISSUE TITLE
metagenomics_pooling_notebook: Assay type needs to be changed to 'Metagenomic' replacing 'Metagenomics' in Sample Sheet Generation

### ISSUE THREAD

**Issue by caiemmtri** [biocore/metagenomics_pooling_notebook#130]
The SPP currently expects the sample sheet 'Assay' to contain 'Metagenomic' and the pooling notebook currently expects the assay to be 'Metagenomic**s**'

In the metagenomics_pooling_notebook, 
_Write DataFrame to file, Step 2: format sample sheet data_

metadata = { ....
   'Assay': 'Metagenomic',
}

Currently outputs:
_ErrorMessage: Metagenomic is not a supported Assay_

= The metagenomics_pooling_notebook needs to be changed to a 'Metagenomic' Assay

<img width="400" alt="Screen Shot 2023-06-30 at 11 03 45 AM" src="https://github.com/biocore/metagenomics_pooling_notebook/assets/88509674/54e120ac-cf37-46da-99c5-9a0154aca1bb">

**Comment by charles-cowart** [comment]
Confirmed _METAGENOMICS const is set to 'Metagenomics' in the current master and tests.
