### ISSUE TITLE
Add matrix tube sample accession support for amplicon notebooks. 

### ISSUE THREAD

**Issue by RodolfoSalido** [biocore/metagenomics_pooling_notebook#169]
amplicon notebooks rely on platemaps generated with spreadsheets instead of the new matrix tubes + VisionMate sample accession workflow. Generate new notebook that will allow to use the new matrix tube + VisionMate workflow.

**Comment by charles-cowart** [comment]
@RodolfoSalido Should we work on this issue together or is there another person in the lab one of us can work with? Not sure what your schedule looks like currently.

**Comment by RodolfoSalido** [comment]
I can work on this one. I think most of the codebase is already in metapool, just need to make a notebook and make sure it works well.
