### ISSUE TITLE
SampleSheet generator module runs with warnings. Well_description column broken. 

### ISSUE THREAD

**Issue by RodolfoSalido** [biocore/metagenomics_pooling_notebook#46]
After cloning the current repository and running in JupyterHub, I ran into some runtime warnings around the SampleSheet generator module. 

Here are the watermarks:

![Screen Shot 2021-10-27 at 11 35 54 AM](https://user-images.githubusercontent.com/13193891/139126288-a9d70d8f-ef92-4c66-a87e-eb7547fb35f2.png)

The first warning doesn't recognize the 'Experiment' key in the metadata dictionary:
![Screen Shot 2021-10-27 at 11 33 01 AM](https://user-images.githubusercontent.com/13193891/139126425-7b08570b-7e4b-4c2f-a2e5-e900eddac7d6.png)

After deleting the 'Experiment' key and typing in a 'experiment_design_description', I still get a warning about the 'Well_description' column being empty:

![Screen Shot 2021-10-27 at 11 34 16 AM](https://user-images.githubusercontent.com/13193891/139126659-2974be49-e1a9-4f08-8772-230772e73647.png)

Indeed, after opening the samplesheet file we find that 'Well_description' is empty:

![Screen Shot 2021-10-27 at 11 40 31 AM](https://user-images.githubusercontent.com/13193891/139126964-7a2ef015-aba0-422e-8a18-45e7e035acd2.png)

**Comment by ElDeveloper** [comment]
Thanks for the suggestion @antgonza and for reporting this @RodolfoSalido! I just submitted #49
