### ISSUE TITLE
Reorder columns in amplicon prep

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/metagenomics_pooling_notebook#54]
The order should be:

> sample_name  BARCODE PRIMER  Primer_Plate    Well_ID Plating ExtractionKit_lot       Extraction_robot        TM1000_8_tool   Primer_date     MasterMix_lot   Water_Lot       Processing_robot        TM300_8_tool    TM50_8_tool     Sample_Plate    Project_name    Orig_name       Well_description        EXPERIMENT_DESIGN_DESCRIPTION   LIBRARY_CONSTRUCTION_PROTOCOL   LINKER  PLATFORM        RUN_CENTER      RUN_DATE        RUN_PREFIX      pcr_primers     sequencing_meth target_gene     target_subfragment      center_name     center_project_name     INSTRUMENT_MODEL        runid

**Comment by charles-cowart** [comment]
@ElDeveloper Unless I'm missing something, https://github.com/biocore/metagenomics_pooling_notebook/issues/40 needs to be finished first before this issue can be resolved right? Or do we just want to reorder the columns in amplicon-pooling.ipynb?

**Comment by ElDeveloper** [comment]
Fixed in #56
