### ISSUE TITLE
Negative concentrations from SpectraMax_i3x reader output break normalization functions. 

### ISSUE THREAD

**Issue by RodolfoSalido** [biocore/metagenomics_pooling_notebook#57]
New plate reader can output negative concentrations for samples with really low nucleic acid yields. The negative values break various normalization functions in the notebook. 

Fix is to change read_pico_csv() to limit concentrations to a range of (0,60).

**Comment by antgonza** [comment]
Thank you @RodolfoSalido; how ofter does this happen and how urgent is this?

**Comment by RodolfoSalido** [comment]
It happens often and we believe this could be the cause of some of the metagenomics library prep issues we have been experiencing. I am submitting a pull request with the fix that I suggest but my GitHub maintenance is not as god as it should be :/ 

-Rodolfo

**Comment by RodolfoSalido** [comment]
should be fixed by #58
