### ISSUE TITLE
Add support for metatranscriptomics in samplesheet generator. 

### ISSUE THREAD

**Issue by RodolfoSalido** [biocore/metagenomics_pooling_notebook#70]
The current samplesheet generator doesn't allow for the Assay description to be "Metatranscriptomics". 
![image](https://user-images.githubusercontent.com/13193891/162496396-26ffddcc-984a-4149-bf40-708456999100.png)

> ErrorMessage: Metatranscriptomics is not a supported Assay

Assay is a standard parameter in the [Header] section of sample sheets. I'm not sure if bcl2fastq would complain if it saw 'Metatranscriptomics' in the Assay field.

**Comment by charles-cowart** [comment]
@RodolfoSalido the pipeline uses bcl-convert right now, just an FYI.

**Comment by antgonza** [comment]
solved here https://github.com/biocore/metagenomics_pooling_notebook/pull/72
