### ISSUE TITLE
Input norm + dilution plate functions?

### ISSUE THREAD

**Issue by DrCletusSpucklerMD** [biocore/metagenomics_pooling_notebook#84]
Hello Developers!

We've been having to dilute our gDNA plates a lot recently and would like the following line of code to be added to Section 2.5 Step 4 of the metagenomics_pipeline_MiniPiconorm notebook:

<img width="853" alt="Screen Shot 2022-10-28 at 12 39 27 AM" src="https://user-images.githubusercontent.com/22571541/198531559-11636ae7-313d-45ce-9c99-24a4b0c2315b.png">

The technicians have been adding this line in by hand but it would be nice to codify it. It allows us to feed in a dilution plate into the echo in addition to the sample and water plates. 

Many thanks! 
.
.
.

Also on the topic of dilution plates - the input norm transfer file generated by the format_dna_norm_picklist function currently spits out a file that looks like this with the water transfers on top: 

<img width="877" alt="Screen Shot 2022-10-28 at 12 42 09 AM" src="https://user-images.githubusercontent.com/22571541/198532067-300117e4-3107-4731-8aaa-203d3a1888a3.png">

If it could spit a file with the DNA additions prior the water additions, that would allow the wetlab technicians to visually check that all the DNA actually transfered prior to initiating the water transfer. It's a nice QC. Pretty sure all you need to do is flip the order of these two code snippets:

<img width="654" alt="Screen Shot 2022-10-28 at 12 59 46 AM" src="https://user-images.githubusercontent.com/22571541/198535721-31f9cd8a-628c-4c32-9e6a-73ff2b52d3d2.png">

Many many many thanks,
Helena T.

**Comment by RodolfoSalido** [comment]
Hello 
I discussed this with Helena. 

We will be testing which Source Plate order is optimal for DNA Input Normalization. 

Once we come to a a decision, I can make the necessary changes to the repository and do a pull request. 

Thanks,
Rodolfo

**Comment by DrCletusSpucklerMD** [comment]
Thanks for helping guide me through this Github "Issues" process here,
Rodolfo! I didn't know Github "Issues" existed and got a little overzealous
trying to find a use for it! Exciting.


Thank you both,
Helena

**Comment by antgonza** [comment]
Just to keep everyone on the same page, @charles-cowart (thank you!) issued a PR solving this: https://github.com/biocore/metagenomics_pooling_notebook/issues/84. @RodolfoSalido / @DrCletusSpucklerMD , could you take a look/review? Thank you.
